version: "3.7"

services:
  eti-micro-gateway-app:
    image: laravel-app
    build:
      args:
        user: eti-micro-gateway
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: eti-micro-gateway-app
    restart: unless-stopped
    depends_on:
      - eti-micro-gateway-server
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - eti-micro-gateway-network

  eti-micro-gateway-server:
    image: nginx:alpine
    container_name: eti-micro-gateway-server
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eti-micro-gateway-network

networks:
  eti-micro-gateway-network:
    driver: bridge
